---
# SSH users
ssh_users:
    - user: 'samael'
      shell: '/bin/zsh'
      groups: 'adm'
      # mkpasswd --method=SHA-512
      password: 'MY-SHA-512-PASSWORD-HASH'
      authorized: 'public_keys/ssh_keys.pub'

# Generate additional locales
locales_gen:
  - "uk_UA.UTF-8"

# My software list 
software:
  - jq
  - zsh 
  - git
  - vim
  - ntp
  - mtr
  - curl
  - sudo
  - tree
  - tmux
  - mosh
  - lsof
  - htop
  - iotop
  - iftop
  - iperf
  - ngrep
  - tcpdump

# true|false for UFW Firewall
ufw_enabled: "false"

# ping allow|deny
ufw_ping: "deny"

ufw_allowed_tcp_ports:
  - "80"
  - "443"
  
ufw_allowed_udp_ports:
  - "1:65535"
