---

# Webitel Playbook 
#
# @author Vitaly Kovalyshyn, 2015

- hosts: all
  name: "Install my pretty linux shell"
  tags: ['my-shell']
  gather_facts: no
  roles:
    - { role: 'my-shell' }
    - { role: 'ufw', when: ufw_enabled == 'true' }

- hosts: docker
  name: "Get Docker & Co."
  sudo: true
  tags: ['docker']
  roles:
    - { role: 'docker' }

  tasks:
    - name: "Add SSH user into the docker group"
      user:
        name: '{{ item.user }}'
        groups: 'docker'
        append: yes
      with_items:
        - '{{ ssh_users }}'
      when: ssh_users is defined

