---
# UFW roles for all hosts

- name: 'Install UFW firewall'
  apt: 
    name: ufw
    state: latest

- name: 'Reset UFW firewall'
  ufw:
    state: reset

- name: 'Allow SSH access on instance'
  ufw:
    rule: limit
    name: OpenSSH

- name: 'Open Allowed UDP ports'
  ufw: 
    rule: allow
    port: '{{ item }}'
    proto: udp
  with_items: '{{ ufw_allowed_udp_ports }}'
 
- name: 'Open Allowed TCP ports'
  ufw: 
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items: '{{ ufw_allowed_tcp_ports }}'
     
- name: 'Set to deny incoming requests by default'
  ufw: 
    policy: deny

- name: "Set the DEFAULT_FORWARD_POLICY for docker"
  lineinfile: 
    dest: '/etc/default/ufw'
    regexp: 'DEFAULT_FORWARD_POLICY'
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: 'Turn on UFW'
  ufw: 
    state: enabled
