---

- name: fix permissions
  file:
    path: '/home/{{ item.user }}/'
    owner: '{{ item.user }}'
    group: '{{ item.user }}'
    state: directory
    recurse: yes
  with_items:
    - '{{ ssh_users }}'
  when: ssh_users is defined

- name: restart ssh
  service: 
    name: ssh
    state: restarted
