---
- include: apt.yml
  when: ansible_os_family == 'Debian'

- name: "Add docker repository for YUM"
  shell: "curl -sSL https://get.docker.com/ | sh"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: "Get docker and easy_install with YUM"
  yum: name={{ item }} state=latest
  with_items:
    - docker-engine
    - python-setuptools
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: "Start docker"
  service: name=docker state=started enabled=yes

- name: "Install docker-compose"
  easy_install: name=docker-compose

